### PR TITLE
Update site.css

### PR DESCRIPTION
**Pull request by jdbruxelles**
Hi there, I think that 10px of padding is better for small screen.

### CODE REVIEW

**Comment by jdbruxelles** [comment]
Hi @marijnh,
It looks like you haven't taken a look at this pull request. Do I have to close it? Have a nice weekend.

**Comment by marijnh** [comment]
Oh, sorry. I wasn't watching this repository for some reason (I think for a while github defaulted to not watching new repositories in orgs), so I didn't notice this until you mentioned me.

**Comment by marijnh** [comment]
I think we'll have to override this back to 3px for the narrow-screen media selector, to avoid wasting too much space on phone screens.

**Comment by jdbruxelles** [comment]
No problem. Ok, I totally understand this point of view. I think it would be better for curved screens to have a little extra margin to facilitate readability.

**Comment by marijnh** [comment]
Ugh, indeed, curved screens seem to push the margins into the curve. Not sure who thought that was a good idea.

But 10px remains too much of a margin on a phone screen. How about just using 5px everywhere?

**Comment by marijnh** [comment]
Superseded by #7

**Pull request closed without merging**
